package onl.oss.catalpa.html;

public enum CharClass {
    EMPTY,
    OPENING_BOUNDARY,
    CLOSING_BOUNDARY,
    CRLF,
    CR,
    LF,
    WHITESPACE,
    LATIN_WORD_CHARACTER,
    LATIN_NON_WORD_CHARACTER,
    OPENING_BRACKET,
    CLOSING_BRACKET,
    HYPHEN,
    DIVIDING_PUNCTUATION_MARK,
    MIDDLE_DOT,
    FULL_STOP,
    COMMA,
    INSEPARABLE_CHARACTER,
    JAPANESE,
    OTHER
}
