---
type: blog
siteurl: https://www.example.com
icon: favicon.ico
title: "ブログのサンプル"
description: |
  これはわたしのブログサイトの説明です。
  毎日更新がんばります！
paginate: 12
copyright: © 2024
author: My Name
mailto: name@example.com
options: [ halt ]
---
