---
type: blog
siteurl: https://www.example.com
title: "ブログのサンプル"
description: |
  これはわたしのブログサイトの説明です。
  毎日更新がんばります！
icon: img/sample1.png
paginate: 60
copyright: © 2022
author: My Name
mailto: name@example.com
---
