---
title: サイトのサンプル
siteurl: http://www.example.com
icon: img/sample2.png
author: どこかのだれか
mailto: user@example.com
---

#--header--
<#include "_header.md">

#--sidebar--
<#include "_sidebar.md">
